server:
  port: '${pet-store-application-port}'
  servlet:
    context-path: '/api/v1'

spring:
  application:
    name: 'pet-store'
  datasource:
    url: 'jdbc:mysql://localhost:3306'
    username: '${db-username}'
    password: '${db-password}'
    hikari:
      minimum-idle: 2
      maximum-pool-size: 11
      catalog: petstoreschema
      register-mbeans: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    schemas: petstoreschema

springdoc:
  swagger-ui:
    path: api-docs
  api-docs:
    path: api-docs

cloud:
  aws:
    credentials:
      access-key: AKIAXEW3M2J5FLR7EO4T
      secret-key: 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
    region:
      static: us-east-2
      auto: false
    s3:
      bucket-name: petstore-aws-storage
