server:
  port: '${pet-store-application-port}'
  servlet:
    context-path: '/api/v1'

spring:
  application:
    name: 'pet-store'
  datasource:
    url: 'jdbc:mysql://localhost:3306'
    username: '${db-username}'
    password: '${db-password}'
    hikari:
      minimum-idle: 2
      maximum-pool-size: 11
      catalog: petstoreschema
      register-mbeans: true



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
#  flyway:
#    schemas: petstoreschema

springdoc:
  swagger-ui:
    path: api-docs
  api-docs:
    path: api-docs

      #google id for login with social media
google:
   id: 150394644628-b6rfj7tbi4pv0cguooulnsomi7a4p1qv.apps.googleusercontent.com
secret:
   password: 12345
