server:
  port: '${pet-store-application-port}'
  servlet:
    context-path: '/api/v1'

spring:
  application:
    name: 'pet-store'
  datasource:
    url: 'jdbc:mysql://localhost:3306'
    username: '${db-username}'
    password: '${db-password}'
    hikari:
      minimum-idle: 2
      maximum-pool-size: 11
      catalog: petstoreschema
      register-mbeans: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: ebrahim.elmohamed26@gmail.com
    password: blkcfcvdvuzrbbjn
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    schemas: petstoreschema

springdoc:
  swagger-ui:
    path: api-docs
  api-docs:
    path: api-docs

#google id for login with social media
google:
   id: 150394644628-b6rfj7tbi4pv0cguooulnsomi7a4p1qv.apps.googleusercontent.com
secret:
   password: 12345


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


cloud:
  aws:
    credentials:
      access-key: AKIAXEW3M2J5FLR7EO4T
      secret-key: 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
    region:
      static: us-east-2
      auto: false
    s3:
      bucket-name: petstore-aws-storage

