<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style type="text/css">
    body {
        background-color: #88BDBF;
        margin: 0px;
    }
</style>

<body>


<table border="0" width="50%"
       style="margin:auto;padding:30px;background-color: #F3F3F3;border:1px solid #6972eb; font-family: system-ui;">
    <tr>
        <td>
            <table border="0" width="100%">
                <tr>
                    <td>
                        <h1><img style="margin-left: 155px;
    width: 121px;" src="https://i.ibb.co/V3G3TqC/logo.png"></h1>
                    </td>
                    <!-- <td>
                        <p style="text-align: right;"><a href="https://nicesnippets.com/" target="_blank"
                                style="font-family: system-ui;text-decoration: none;">View In Website</a></p>
                    </td> -->
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" cellpadding="0" cellspacing="0"
                   style="text-align:center;width:100%;background-color: #fff;">
                <tr>
                    <td style="background-color:#6972eb;height:100px;font-size:50px;color:#fff;"><i
                                class="fa fa-envelope-o" aria-hidden="true"></i></td>
                </tr>
                <tr>
                    <td>
<#--                        <h1 style="padding-top:25px;">Contact US</h1>-->
                        <h1 style="font-family: system-ui; margin:auto;">Thanks ${contactUsDTO.name} For contacting us</h1>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-family: system-ui;padding:0px 100px;">
                            ${contactUsDTO.message}
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <button
                                style="font-family: system-ui;margin:10px 0px 30px 0px;border-radius:4px;padding:10px 20px;border: 0;color:#fff;background-color:#6972eb; ">
                            Back To PetStore</button>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" width="100%" style="border-radius: 5px;text-align: center;">
                <tr>
                    <td>
                        <h3 style="font-family: system-ui;margin-top:10px;">Stay in touch</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <!-- <div style="margin-top:20px;">
                            <a href="#" style="text-decoration: none;"><span class="twit"
                                    style="padding:10px 9px;background-color:#4099FF;color:#fff;border-radius:50%;"><i
                                        class="fa fa-twitter" aria-hidden="true"
                                        style="height:20px;width:20px;"></i></span></a>
                            <a href="#" style="text-decoration: none;"><span class="fb"
                                    style="padding:10px 9px;background-color: #3B5998;color:#fff;border-radius:50%;"><i
                                        class="fa fa-facebook" aria-hidden="true"
                                        style="height:20px;width:20px;"></i></span></a>
                            <a href="#" style="text-decoration: none;"><span class="msg"
                                    style="padding:10px 9px;background-color: #FFC400;color:#fff;border-radius:50%;""><i class="
                                    fa fa-envelope-o" aria-hidden="true"
                                    style="height:20px;width:20px;"></i></span></a>
                        </div> -->
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="margin-top: 20px;">
                            <span style="font-family: system-ui;font-size:12px;">PetStore Team</span><br>
                            <span style="font-family: system-ui;font-size:12px;">Copyright © 2021 PetStore</span>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>

</html>
